Update pipeline electron-linux

diff --git a/.harness/electronlinux.yaml b/.harness/electronlinux.yaml
--- a/.harness/electronlinux.yaml
+++ b/.harness/electronlinux.yaml
@@ -370,3 +370,35 @@ pipeline:
                   when:
                     stageStatus: All
                   failureStrategies: []
+              - step:
+                  type: Run
+                  name: Setup Goma
+                  identifier: Setup_Goma
+                  spec:
+                    shell: Sh
+                    command: |-
+                      #!/bin/bash -eo pipefail
+                      echo 'export NUMBER_OF_NINJA_PROCESSES=300' >> $BASH_ENV
+                      if [ "`uname`" == "Darwin" ]; then
+                        echo 'ulimit -n 10000' >> $BASH_ENV
+                        echo 'sudo launchctl limit maxfiles 65536 200000' >> $BASH_ENV
+                      fi
+                      if [ ! -z "$RAW_GOMA_AUTH" ]; then
+                        echo $RAW_GOMA_AUTH > ~/.goma_oauth2_config
+                      fi
+                      git clone https://github.com/electron/build-tools.git
+                      cd build-tools
+                      npm install
+                      mkdir third_party
+                      node -e "require('./src/utils/goma.js').downloadAndPrepare({ gomaOneForAll: true })"
+                      export GOMA_FALLBACK_ON_AUTH_FAILURE=true
+                      third_party/goma/goma_ctl.py ensure_start
+                      if [ ! -z "$RAW_GOMA_AUTH" ] && [ "`third_party/goma/goma_auth.py info`" != "Login as Fermi Planck" ]; then
+                        echo "WARNING!!!!!! Goma authentication is incorrect; please update Goma auth token."
+                        exit 1
+                      fi
+                      echo 'export GN_GOMA_FILE='`node -e "console.log(require('./src/utils/goma.js').gnFilePath)"` >> $BASH_ENV
+                      echo 'export LOCAL_GOMA_DIR='`node -e "console.log(require('./src/utils/goma.js').dir)"` >> $BASH_ENV
+                      echo 'export GOMA_FALLBACK_ON_AUTH_FAILURE=true' >> $BASH_ENV
+                      cd ..
+                      touch "${TMPDIR:=/tmp}"/.goma-ready
