Update pipeline test-electron

diff --git a/.harness/testelectron.yaml b/.harness/testelectron.yaml
--- a/.harness/testelectron.yaml
+++ b/.harness/testelectron.yaml
@@ -185,6 +185,74 @@ pipeline:
                       spec:
                         paths:
                           - src/junit
+              - step:
+                  type: Run
+                  name: step-verify-mksnapshot
+                  identifier: stepverifymksnapshot
+                  spec:
+                    shell: Sh
+                    command: |2-
+                            if [ "$IS_ASAN" != "1" ]; then
+                              cd src
+                              if [ "$TARGET_ARCH" == "arm" ] || [ "$TARGET_ARCH" == "arm64" ]; then
+                                python electron/script/verify-mksnapshot.py --source-root "$PWD" --build-dir out/Default --snapshot-files-dir $PWD/cross-arch-snapshots
+                              else
+                                python electron/script/verify-mksnapshot.py --source-root "$PWD" --build-dir out/Default
+                              fi
+                            fi
+              - step:
+                  type: Run
+                  name: step-verify-chromedriver
+                  identifier: stepverifychromedriver
+                  spec:
+                    shell: Sh
+                    command: |2-
+                            if [ "$IS_ASAN" != "1" ]; then
+                              cd src
+                              python electron/script/verify-chromedriver.py --source-root "$PWD" --build-dir out/Default
+                            fi
+              - step:
+                  type: Run
+                  name: step-maybe-notify-slack-failure
+                  identifier: stepmaybenotifyslackfailure
+                  spec:
+                    shell: Sh
+                    command: |2-
+                            if [ "$NOTIFY_SLACK" == "true" ]; then
+                              export MESSAGE="Build failed for *<$CIRCLE_BUILD_URL|$CIRCLE_JOB>* nightly build from *$CIRCLE_BRANCH*."
+                              curl -g -H "Content-Type: application/json" -X POST \
+                              -d "{\"text\": \"$MESSAGE\", \"attachments\": [{\"color\": \"#FC5C3C\",\"title\": \"$CIRCLE_JOB nightly build results\",\"title_link\": \"$CIRCLE_BUILD_URL\"}]}" $SLACK_WEBHOOK
+                            fi
+                  when:
+                    stageStatus: Success
+                    condition: <+pipeline.stages.cond.spec.execution.steps.echo.status> == "FAILED"
+                  failureStrategies: []
+              - step:
+                  type: Run
+                  name: step-maybe-cleanup-arm64-mac
+                  identifier: stepmaybecleanuparm64mac
+                  spec:
+                    shell: Sh
+                    command: |2-
+                            if  [ "$TARGET_ARCH" == "arm64" ] &&[ "`uname`" == "Darwin" ]; then
+                              killall Electron || echo "No Electron processes left running"
+                              killall Safari || echo "No Safari processes left running"
+                              rm -rf ~/Library/Application\ Support/Electron*
+                              rm -rf ~/Library/Application\ Support/electron*
+                              security delete-generic-password -l "Chromium Safe Storage" || echo "✓ Keychain does not contain password from tests"
+                              security delete-generic-password -l "Electron Test Main Safe Storage" || echo "✓ Keychain does not contain password from tests"
+                              security delete-generic-password -a "electron-test-safe-storage" || echo "✓ Keychain does not contain password from tests"
+                              security delete-generic-password -l "electron-test-safe-storage Safe Storage" || echo "✓ Keychain does not contain password from tests"
+                            elif [ "$TARGET_ARCH" == "arm" ] || [ "$TARGET_ARCH" == "arm64" ]; then
+                              XVFB=/usr/bin/Xvfb
+                              /sbin/start-stop-daemon --stop --exec $XVFB || echo "Xvfb not running"
+                              pkill electron || echo "electron not running"
+                              rm -rf ~/.config/Electron*
+                              rm -rf ~/.config/electron*
+                            fi
+                  when:
+                    stageStatus: All
+                  failureStrategies: []
     - stage:
         name: Builds
         identifier: Builds
