Update pipeline test-electron

diff --git a/.harness/testelectron.yaml b/.harness/testelectron.yaml
--- a/.harness/testelectron.yaml
+++ b/.harness/testelectron.yaml
@@ -32,6 +32,69 @@ pipeline:
                   spec:
                     shell: Sh
                     command: rm -rf src/electron
+              - step:
+                  type: Run
+                  name: step-install-gnutar-on-mac
+                  identifier: stepinstallgnutaronmac
+                  spec:
+                    shell: Sh
+                    command: |2-
+                            if [ "`uname`" == "Darwin" ]; then
+                              if [ ! -d /usr/local/Cellar/gnu-tar/ ]; then
+                                brew update
+                                brew install gnu-tar
+                              fi
+                              ln -fs /usr/local/bin/gtar /usr/local/bin/tar
+                            fi
+              - step:
+                  type: Run
+                  name: install-python2-mac
+                  identifier: installpython2mac
+                  spec:
+                    shell: Sh
+                    command: |-
+                      if [ "`uname`" == "Darwin" ] && [ "$IS_ELECTRON_RUNNER" != "1" ]; then
+                          if [ ! -f "python-downloads/python-2.7.18-macosx10.9.pkg" ]; then
+                          mkdir python-downloads
+                          echo 'Downloading Python 2.7.18'
+                          curl -O https://dev-cdn.electronjs.org/python/python-2.7.18-macosx10.9.pkg
+                          mv python-2.7.18-macosx10.9.pkg python-downloads
+                          else
+                          echo 'Using Python install from cache'
+                          fi
+                          sudo installer -pkg python-downloads/python-2.7.18-macosx10.9.pkg -target /        
+                      fi
+              - step:
+                  type: Run
+                  name: step-setup-goma-for-build
+                  identifier: stepsetupgomaforbuild
+                  spec:
+                    shell: Sh
+                    command: |2-
+                            echo 'export NUMBER_OF_NINJA_PROCESSES=300' >> $BASH_ENV
+                            if [ "`uname`" == "Darwin" ]; then
+                              echo 'ulimit -n 10000' >> $BASH_ENV
+                              echo 'sudo launchctl limit maxfiles 65536 200000' >> $BASH_ENV
+                            fi
+                            if [ ! -z "$RAW_GOMA_AUTH" ]; then
+                              echo $RAW_GOMA_AUTH > ~/.goma_oauth2_config
+                            fi
+                            git clone https://github.com/electron/build-tools.git
+                            cd build-tools
+                            npm install
+                            mkdir third_party
+                            node -e "require('./src/utils/goma.js').downloadAndPrepare({ gomaOneForAll: true })"
+                            export GOMA_FALLBACK_ON_AUTH_FAILURE=true
+                            third_party/goma/goma_ctl.py ensure_start
+                            if [ ! -z "$RAW_GOMA_AUTH" ] && [ "`third_party/goma/goma_auth.py info`" != "Login as Fermi Planck" ]; then
+                              echo "WARNING!!!!!! Goma authentication is incorrect; please update Goma auth token."
+                              exit 1
+                            fi
+                            echo 'export GN_GOMA_FILE='`node -e "console.log(require('./src/utils/goma.js').gnFilePath)"` >> $BASH_ENV
+                            echo 'export LOCAL_GOMA_DIR='`node -e "console.log(require('./src/utils/goma.js').dir)"` >> $BASH_ENV
+                            echo 'export GOMA_FALLBACK_ON_AUTH_FAILURE=true' >> $BASH_ENV
+                            cd ..
+                            touch "${TMPDIR:=/tmp}"/.goma-ready
     - parallel:
         - stage:
             name: electron-tests
